### PR TITLE
remove IDE settings

### PR DESCRIPTION
**Pull request by ornithos**
Solves #4

### CODE REVIEW

**Comment by ornithos** [comment]
@quest-bot-dev loot

**Comment by ornithos** [comment]
@quest-bot-dev loot #4

**Comment by ornithos** [comment]
@quest-bot-dev loot #4

**Comment by monipan2817** [comment]
@quest-bot-dev stash 20

**Comment by monipan2817** [comment]
@quest-bot-dev stash twenty

**Comment by monipan2817** [comment]
@quest-bot-dev abort

**Comment by ornithos** [comment]
@quest-bot reward @ornithos

**Comment by ornithos** [comment]
@quest-bot-dev reward @ornithos

**Review by monipan2817 — APPROVED** [review]

**Comment by ornithos** [comment]
@quest-bot-dev loot

**Pull request merged**
